[package]
name = "game-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.26.0", features = ["extension-module"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
